use_kit_for_tasks: False
environment: PRODUCTION
projects:
    collection:
        instruction_path: "content/instructions/collection_instruction.html"
        log_level: DEBUG
        tasks_path: "content/prod_tasks/collection.tsv"
        reward_per_assignment: 0.01
        overlap: 1
    bbox_labeling:
        instruction_path: "content/instructions/bbox_labeling_instruction.html"
        log_level: DEBUG
        tasks_path: "content/prod_tasks/bbox_labeling.tsv"
        reward_per_assignment: 0.01
        overlap: 1
    ocr:
        instruction_path: "content/instructions/ocr_instruction.html"
        log_level: DEBUG
        tasks_path: "content/prod_tasks/ocr.tsv"
        reward_per_assignment: 0.01
        overlap: 1
